config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'

  # get 'histories/new'

  # get 'diamonds/index'
  # root 'diamonds#index'
  resources :diamonds
  resources :histories

 
end

app/models/diamond.rb
class Diamond < ActiveRecord::Base
end

app/models/history.rb
class History < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/diamonds_controller.rb
class DiamondsController < ApplicationController
  def index
    @diamonds = Diamond.all
  end
  
  def create
    @diamond = Diamond.new(diamond_params)
    @diamond.save
    redirect_to root_path , notice: 'データを保存しました'
  end
  
  private
  def diamond_params
    params.require(:diamond).permit(:shape, :weight, :color, :cut, :pol, :sym, :fluo, :lab,
                                    :depth, :table, :measurements, :culet, :girdle, :list_price, 
                                    :rap, :sale_price, :total_price, :location, :cert, :clar)
  end
  
end

app/controllers/histories_controller.rb
class HistoriesController < ApplicationController
  def new
  end
  
  def show
  end
  
  def index
    @histrories = History.all
  end
  
    def create
    @history = History.new(diamond_params)
    @history.save
    redirect_to root_path , notice: 'データを保存しました'
  end
  
  private
  def diamond_params
    params.require(:history).permit(:date, :weight, :color, :list_price, :clar)
  end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/diamonds_helper.rb
module DiamondsHelper
end

app/views/diamonds/index.html.erb
<h1>Diamonds#index</h1>
<table class="table table-bordered">
  <tr>
    <th>Culet</th>
    <th>Color</th>
    <th>Clar</th>
    <th>List Price</th>
  </tr>
  <% @diamonds.each do |diamond| %>
    <tr>
      <td><%= diamond.culet %></td>
      <td><%= diamond.color %></td>
      <td><%= diamond.clar %></td>
      <td><%= diamond.list_price %></td>
    </tr>
  <% end %>
</table>


<%= form_for(Diamond.new) do |f| %>
    Shape:
    <%= f.text_field :shape %>
    
    Weight:
    <%= f.text_field :weight %>
    
    Color:
    <%= f.text_field :color %>
    
    Clar:
    <%= f.text_field :clar %>
    
    Cut:
    <%= f.text_field :cut %>
    
    Pol:
    <%= f.text_field :pol %>
    
    Sym:
    <%= f.text_field :sym %>
    
    Fluo:
    <%= f.text_field :fluo %>
    
    Lab:
    <%= f.text_field :lab %>
    
    Depth:
    <%= f.text_field :depth %>
    
    Table:
    <%= f.text_field :table %>
    
    Measurements:
    <%= f.text_field :measurements %>
    
    Culet:
    <%= f.text_field :culet %>
    
    Girdle:
    <%= f.text_field :girdle %>
    
    List Price:
    <%= f.text_field :list_price %>
    
    % Rap:
    <%= f.text_field :rap %>
    
    Sale Price:
    <%= f.text_field :sale_price %>
    
    Total Price:
    <%= f.text_field :total_price %>
    
    Location:
    <%= f.text_field :location %>
    
    Cert#:
    <%= f.text_field :cert %>
    
    <%= f.submit %>
<% end %>



 

app/views/histories/index.html.erb
<h1>Diamonds#Chart</h1>

<%= line_chart History.group(:clar).group(:date).maximum(:list_price) %>
<%#= line_chart @histories.map{|history|
    {name: history.clar, data: history.feats.group(:date).list_price}
} %>

<table class="table table-bordered">
  <tr>
    <th>Date</th>
    <th>Weight</th>
    <th>Color</th>
    <th>Clar</th>
    <th>List Price</th>
  </tr>
  <% @histrories.each do |history| %>
    <tr>
      <td><%= history.date %></td>
      <td><%= history.weight %></td>
      <td><%= history.color %></td>
      <td><%= history.clar %></td>
      <td><%= history.list_price %></td>
    </tr>
  <% end %>
</table>

<%= form_for(History.new) do |f| %>
    Date:
    <%= f.date_field :date %>
    
    Weight:
    <%= f.text_field :weight %>
    
    Color:
    <%= f.text_field :color %>
    
    Clar:
    <%= f.text_field :clar %>

    List Price:
    <%= f.text_field :list_price %>

    
    <%= f.submit %>
<% end %>

app/views/histories/new.html.erb
<h1>Histories#new</h1>
<p>Find me in app/views/histories/new.html.erb</p>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="container">
    <%= link_to "Diamonds", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Chart",   histories_path %></li>
        <li><%= link_to "Inventory", diamonds_path %></li>
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help",   '#' %></li>
        <li><%= link_to "Log in", '#' %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DiamondB</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>